# Generated by Django 5.0.2 on 2024-02-26 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=200)),
                ('admin_password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('mentor_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('mentor_name', models.CharField(max_length=200)),
                ('mentor_password', models.CharField(max_length=128)),
                ('mentor_phone', models.CharField(blank=True, default='Value not set', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=200)),
                ('student_password', models.CharField(max_length=128)),
                ('student_address', models.TextField(blank=True, default='Value not set', null=True)),
                ('student_phone', models.CharField(blank=True, default='Value not set', max_length=15, null=True)),
                ('student_course', models.CharField(blank=True, default='Value not set', max_length=15, null=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intervention_system.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(auto_now_add=True)),
                ('report_category', models.CharField(max_length=100)),
                ('report_text', models.TextField()),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intervention_system.mentor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intervention_system.student')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_venue', models.CharField(max_length=100)),
                ('appointment_time', models.TimeField()),
                ('appointment_description', models.TextField(blank=True, default='-', null=True)),
                ('appointment_purpose', models.TextField(blank=True, default='-', null=True)),
                ('appointment_status', models.CharField(default='Pending...', max_length=8)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intervention_system.mentor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intervention_system.student')),
            ],
        ),
    ]
