# Generated by Django 5.0.2 on 2024-02-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervention_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='mentor_sub',
            field=models.CharField(blank=True, default='Value not set', max_length=15),
        ),
    ]
